### ISSUE TITLE
Todo App 요구사항 명세서

### ISSUE THREAD

**Issue by leejungho9** [leejungho9/MungDoList#2]
## 만들고자 하는 기능
Todo 생성 기능
Todo 수정 기능
Todo 삭제 기능
처음 Main 화면은 하루에 한 번만 보여주는 기능 

## 해야 할 작업

- [x] component 나누기
- [x] html 및 css 작업
- [x] redux 사용하여 상태 관리
- [x] json-server 로 서버와 통신

## 예상 작업 시간 
7 day..

**Comment by leejungho9** [comment]
Todo App 요구사항 명세서
